version: '3.9'

services:
  product_api:
    image: product_api:1.0
    container_name: product_api.v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # ConnectionStrings__DefaultConnection: "Host=product_db;Database=productapi;Username=myusr;Password=mypwd"
    networks: 
      - product_api_network
    depends_on:
      product_db:
        condition: service_healthy    
  
  product_db:
    image: postgres:latest
    container_name: product_db.v1
    restart: always
    environment:
      POSTGRES_DB: productapi
      POSTGRES_USER: myusr
      POSTGRES_PASSWORD: mypwd
    ports:
      - "5432:5432"
    networks:
      - product_api_network
    volumes:
      - product_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  product_api_network:
    driver: bridge

volumes:
  product_data: