@base_url = http://localhost:5001
@url_path = api/products

### Get all products
GET {{base_url}}/{{url_path}}

### Get product by id
GET {{base_url}}/{{url_path}}/{id}

### Create a new product
POST {{base_url}}/{{url_path}}
Content-Type: application/json

{
    "Name": "New Product"
}

### Update product by id (replace {id} with an actual product id)
PUT {{base_url}}/{{url_path}}/{id}
Content-Type: application/json

{
    "Id": "{id}",
    "Name": "Updated Product"
}

### Delete product by id (replace {id} with an actual product id)
DELETE {{base_url}}/{{url_path}}/{id}
